// AUTO-GENERATED by scripts/build-referenceable-stories.mjs. DO NOT EDIT BY HAND.
// Per-industry Searce case studies shown in the Intelligence Feed "Proof" tab
// alongside the live case-study matches.
//
// Every URL here is a real, verified searce.com/cs-N-detail page — sourced from
// the curated pain-point -> case-study sheet, never constructed from an ID.

export const VERIFIED_SEARCE_LINKS: Record<
	string,
	{ title: string; url: string; metrics: string }[]
> = {
	FSI: [
		{
			title: "PasaJob saves 62% on Cloud Costs with Searce-led Google Cloud Migration",
			url: "https://www.searce.com/cs-128-detail",
			metrics: "",
		},
		{
			title: "Searce Helps Harappa to Encrypt Data at Rest and Data at Transit of the MongoDB Atlas Database",
			url: "https://www.searce.com/cs-61-detail",
			metrics: "",
		},
		{
			title: "How EarlySalary used AWS to Improve its Response Time for Reports by over 50%",
			url: "https://www.searce.com/cs-34-detail",
			metrics: "",
		},
		{
			title: "Europ Assistance: RePlatforming, Migrating Databases from On-Prem Servers to RDS-MySQL",
			url: "https://www.searce.com/cs-66-detail",
			metrics: "",
		},
		{
			title: "ICICI Prudential Life Insurance: Using Vision API to efficiently process thousands of documents",
			url: "https://www.searce.com/cs-10-detail",
			metrics: "",
		},
		{
			title: "How Remitano Transformed its Data Timeliness by Reducing Query Speeds by 8 Hours",
			url: "https://www.searce.com/cs-134-detail",
			metrics: "",
		},
		{
			title: "Searce Modernizes Data Infrastructure for a Century-Old US-Based Community Bank",
			url: "https://www.searce.com/cs-97-detail",
			metrics: "",
		},
		{
			title: "Searce Drives Efficiency and Innovation for Fintech Leader Finder",
			url: "https://www.searce.com/cs-106-detail",
			metrics: "",
		},
		{
			title: "From Legacy Databases to Real-Time Growth: How Searce Helped a FinTech Giant Unlock Potential",
			url: "https://www.searce.com/cs-103-detail",
			metrics: "",
		},
	],
	HLS: [
		{
			title: "Big Savings, Bigger Scale: Pharma Giant's Move from IBM Netezza to Google Cloud BigQuery",
			url: "https://www.searce.com/cs-138-detail",
			metrics: "",
		},
		{
			title: "USV Leverages AWS Data Lake for Analytics and Business Insights",
			url: "https://www.searce.com/cs-69-detail",
			metrics: "",
		},
		{
			title: "Empowering 50% Faster Drug Discovery with Automated Protein Analysis for a Leading Biotech",
			url: "https://www.searce.com/cs-114-detail",
			metrics: "",
		},
		{
			title: "Searce helps Redcliffe Labs Improve the Cloud Security Posture Through the Use of Google Cloud Native Security Services",
			url: "https://www.searce.com/cs-131-detail",
			metrics: "",
		},
		{
			title: "Searce's Solution Helped EPL to Perform Cost Effective IoT & SAP Data Analytics on AWS",
			url: "https://www.searce.com/cs-76-detail",
			metrics: "",
		},
		{
			title: "Enabling Preventive Maintenance for a Global Steel Manufacturer",
			url: "https://www.searce.com/cs-118-detail",
			metrics: "",
		},
		{
			title: "IndiaFirst Life Works With Searce to Achieve IT Infrastructure Transformation",
			url: "https://www.searce.com/cs-91-detail",
			metrics: "",
		},
	],
	MCM: [
		{
			title: "Searce Empowers Leading Global Steel Manufacturer with Real-Time Data Insights",
			url: "https://www.searce.com/cs-96-detail",
			metrics: "",
		},
		{
			title: "Revving Up Efficiency: Leading Vehicle Inspection App Slashes Training Times by 46% with A100 GPUs for Faster Automotive AI",
			url: "https://www.searce.com/cs-109-detail",
			metrics: "",
		},
		{
			title: "Enabling Preventive Maintenance for a Global Steel Manufacturer",
			url: "https://www.searce.com/cs-118-detail",
			metrics: "",
		},
		{
			title: "Searce Helps Indonesian Manufacturing Giant Achieve a 50% Boost to Performance and 30% Cost Savings",
			url: "https://www.searce.com/cs-112-detail",
			metrics: "",
		},
		{
			title: "Largest Motorcycle Manufacturer uses GCP to Create Chatbots for Internal and External Efficiency Gains",
			url: "https://www.searce.com/cs-15-detail",
			metrics: "",
		},
		{
			title: "Searce Helped Razor Group by Leveraging AWS Lambda Which Helped Them Increase the Scalability and Efficiency",
			url: "https://www.searce.com/cs-86-detail",
			metrics: "",
		},
	],
	PSE: [
		{
			title: "Searce Transforms Success Resources' GCP Architecture to Increase Security, Operational Efficiency, and Reliability",
			url: "https://www.searce.com/cs-89-detail",
			metrics: "",
		},
		{
			title: "Searce Helps IIT Madras Leverage Scalable Infrastructure and Achieve Lean Response Time",
			url: "https://www.searce.com/cs-59-detail",
			metrics: "",
		},
		{
			title: "Mindvalley Achieves Improved CI/CD, Automation and Better Security After Migrating to Google Cloud",
			url: "https://www.searce.com/cs-57-detail",
			metrics: "",
		},
		{
			title: "Searce Helps Static Media Increase Content Throughput by 3.5x with AI-Powered Efficiency",
			url: "https://www.searce.com/cs-113-detail",
			metrics: "",
		},
	],
	RCE: [
		{
			title: "Tabsquare and Searce: Scaling Up with Google Cloud to Deliver Seamless Ordering Experiences and Ensure 100% Uptime",
			url: "https://www.searce.com/cs-119-detail",
			metrics: "",
		},
		{
			title: "Vyapar: Rearchitecturing the solution to reduce latency and optimize performance with Searce and AWS",
			url: "https://www.searce.com/cs-54-detail",
			metrics: "",
		},
		{
			title: "Yaantra partners with Searce & Google Cloud to help consumers with a single window stopover for smart gadgets in India",
			url: "https://www.searce.com/cs-51-detail",
			metrics: "",
		},
		{
			title: "How An E-commerce Brand Built a Scalable Infrastructure for its Increasing Demands using AWS",
			url: "https://www.searce.com/cs-39-detail",
			metrics: "",
		},
		{
			title: "Bizzy Group Unlocks Business Opportunities with Data on AWS",
			url: "https://www.searce.com/cs-6-detail",
			metrics: "",
		},
		{
			title: "Searce helps Omnichannel Retail Leader Boost E-Commerce with Automated Image Metadata Generation using AWS",
			url: "https://www.searce.com/cs-124-detail",
			metrics: "",
		},
		{
			title: "Prime Captain Prioritizes Innovation and Ensures Smooth Scaling with Searce and AWS",
			url: "https://www.searce.com/cs-56-detail",
			metrics: "",
		},
		{
			title: "Mindvalley Achieves Improved CI/CD, Automation and Better Security After Migrating to Google Cloud",
			url: "https://www.searce.com/cs-57-detail",
			metrics: "",
		},
	],
	TMEG: [
		{
			title: "inshorts: Delivering mobile news solutions with Google Cloud to serve Indian readers better",
			url: "https://www.searce.com/cs-3-detail",
			metrics: "",
		},
		{
			title: "To put a stop to 'fake news', Logically partners with Searce to scale cost-effectively with Preemptible Virtual Machines on Google Cloud",
			url: "https://www.searce.com/cs-2-detail",
			metrics: "",
		},
		{
			title: "A Geo-Spatial Analytical Industry Leader Modernized Their Applications Landscape to be Agile, Resilient and Scalable With the Help of AWS Native Services",
			url: "https://www.searce.com/cs-74-detail",
			metrics: "",
		},
		{
			title: "Rapido: Finding the quickest route to success with Google",
			url: "https://www.searce.com/cs-5-detail",
			metrics: "",
		},
		{
			title: "How Ugam Could Reduce its Query Execution Time using the Power of AWS",
			url: "https://www.searce.com/cs-32-detail",
			metrics: "",
		},
		{
			title: "Scribendi: Transforming Online Editing and Proofreading Services with Google Cloud and Searce",
			url: "https://www.searce.com/cs-88-detail",
			metrics: "",
		},
		{
			title: "Yaantra partners with Searce & Google Cloud to help consumers with a single window stopover for smart gadgets in India",
			url: "https://www.searce.com/cs-51-detail",
			metrics: "",
		},
		{
			title: "Prime Captain Prioritizes Innovation and Ensures Smooth Scaling with Searce and AWS",
			url: "https://www.searce.com/cs-56-detail",
			metrics: "",
		},
	],
	TSS: [
		{
			title: "How OpsRamp used Google Cloud to Integrate & Deploy their Pods with Minimal Operational Overheads",
			url: "https://www.searce.com/cs-27-detail",
			metrics: "",
		},
		{
			title: "Searce Helps IIT Madras Leverage Scalable Infrastructure and Achieve Lean Response Time",
			url: "https://www.searce.com/cs-59-detail",
			metrics: "",
		},
		{
			title: "Product Development Tech Solutions Company Leverages Searce Expertise and AWS Technologies to Ensure Scalable, Cost-Effective and Secure Deployments",
			url: "https://www.searce.com/cs-55-detail",
			metrics: "",
		},
		{
			title: "How Searce Helped Truegy Automate Deployment and Achieve Cost Optimization",
			url: "https://www.searce.com/cs-58-detail",
			metrics: "",
		},
		{
			title: "Aruba leverages AWS, DevOps tools to build, deploy and manage EKS Services",
			url: "https://www.searce.com/cs-53-detail",
			metrics: "",
		},
		{
			title: "Xeno Runs Their AI Powered CRM Through the Infrastructure and Apps Hosted on AWS",
			url: "https://www.searce.com/cs-72-detail",
			metrics: "",
		},
		{
			title: "How Convo Reduced its Costs and Created a Better User Experience by Leveraging G Suite",
			url: "https://www.searce.com/cs-26-detail",
			metrics: "",
		},
		{
			title: "Mindvalley Achieves Improved CI/CD, Automation and Better Security After Migrating to Google Cloud",
			url: "https://www.searce.com/cs-57-detail",
			metrics: "",
		},
		{
			title: "Scribendi: Transforming Online Editing and Proofreading Services with Google Cloud and Searce",
			url: "https://www.searce.com/cs-88-detail",
			metrics: "",
		},
		{
			title: "How Searce Helped SourseAI Unlock Growth Potential With Google Cloud",
			url: "https://www.searce.com/cs-100-detail",
			metrics: "",
		},
		{
			title: "From Cost Strain to Scalable Growth: How Searce Helped GivePanel Conquer Their Cloud Challenges",
			url: "https://www.searce.com/cs-99-detail",
			metrics: "",
		},
		{
			title: "Learn How Searce Assisted Ayoconnect in Accommodating a One-thousand-fold Surge in Apigee API Hits",
			url: "https://www.searce.com/cs-70-detail",
			metrics: "",
		},
		{
			title: "Beyond Upgrades: A Strategic Approach to Insurun's Cloud Infrastructure with Searce",
			url: "https://www.searce.com/cs-105-detail",
			metrics: "",
		},
		{
			title: "Searce Helped Kissht Drive Business Agility by Using AWS EKS Services",
			url: "https://www.searce.com/cs-85-detail",
			metrics: "",
		},
		{
			title: "How Searce Helped Aruba Modernize their Databases with AWS DynamoDB",
			url: "https://www.searce.com/cs-94-detail",
			metrics: "",
		},
	],
	TTL: [
		{
			title: "India's Leading Logistics Company Migrated SAP Data Analytics Workloads on AWS to Improve Consignment Level Business Insights",
			url: "https://www.searce.com/cs-75-detail",
			metrics: "",
		},
		{
			title: "Rapido: Finding the quickest route to success with Google",
			url: "https://www.searce.com/cs-5-detail",
			metrics: "",
		},
		{
			title: "How Caravel Logistics Improved their Productivity using Google Workspace",
			url: "https://www.searce.com/cs-44-detail",
			metrics: "",
		},
		{
			title: "Searce Helps Kaebox Leverage Google Maps Platform to Elevate Delivery Experience",
			url: "https://www.searce.com/cs-104-detail",
			metrics: "",
		},
		{
			title: "Driving Logistics Innovation with Searce & Google Cloud",
			url: "https://www.searce.com/cs-92-detail",
			metrics: "",
		},
		{
			title: "How Searce Helped Ryde Technologies Enhance Customer Experience and Drive Growth in New Markets",
			url: "https://www.searce.com/cs-82-detail",
			metrics: "",
		},
		{
			title: "Rebel Foods: Pinpointing customers for food delivery with Google Maps Platform",
			url: "https://www.searce.com/cs-8-detail",
			metrics: "",
		},
	],
};
