// AUTO-GENERATED by scripts/build-referenceable-stories.mjs. DO NOT EDIT BY HAND.
// Static per-industry referenceable stories shown in the Intelligence Feed
// "Proof" tab as a supplement to the live case-study matches.

export const VERIFIED_SEARCE_LINKS: Record<
	string,
	{ title: string; url: string; metrics: string }[]
> = {
	FSI: [
		{
			title: "Insurun: Infra and Apps deployment to GKE Infra v1.25",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Insurun is running on the latest GKE version 1.25.",
		},
		{
			title: "Toorak Capital Partners: AWS to Google Cloud Migration & Code Refactoring",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Security: Cloud armor securing the infra from any DDOS/OWASP Top 10 attacks.",
		},
		{
			title: "Early Salary: Re-Architecting the Infrastructure for AutoScaling",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Response time for reports improved by over 50%.",
		},
	],
	MISC: [
		{
			title: "implementation and deployment of the Search API",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"GenAI-powered search engine cut search response times in half from 300 ms to 150 ms Advanced filtering results, ranking…",
		},
		{
			title: "Integrating SaaS Product on GCP Marketplace",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Easy 1 Click SaaS Database based offering over GCP Marketplace.",
		},
		{
			title: "Content Stack: GCP implementation of applications using GKE contentstack.com",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"2x Quicker turnaround time with automated application deployments Centralized data in GCP for improved customer experience.",
		},
	],
	TMEG: [
		{
			title: "Containerized and deployed API",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Achieved 99% accuracy in document categorization and 96% in field extraction Electronic data extraction minimizes human error…",
		},
		{
			title: "One to One mapping of Streamers to VM: Improved Latency for Video Streaming on Blockchain",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"~50% Cost Reduction - Ingestor auto scaling allows the platform to scale out and scale down the Ingestor servers based on the…",
		},
		{
			title: "The born in cloud news aggregator moved from AWS",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Reduced monthly costs from USD$100K on data analytics alone to USD$20K for the entire infrastructure Improved average user…",
		},
	],
	TTL: [
		{
			title: "Migration of workloads-GCP to reduce overall TCO",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"4 additional services were onboarded and migrated within the project timelines.",
		},
		{
			title: "EMT: Modernizing Infra for a Tours & Travels Website",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"20% optimization in cost from AWS to GCP Reduction in Cloud Spend and overall Infrastructure Cost Increase in the performance…",
		},
		{
			title: "Modernizing Database for a Cab Hailing App",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Latency reduced by 10x with more reliable infrastructure Reduced infra spend a better DR setup Reduced management overhead…",
		},
	],
	RCE: [
		{
			title: "Moglix: On Prem to Google Cloud Platform Migration",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Customer was also able to save around 15-20% in cost.",
		},
		{
			title: "MyAnatomy: AWS to GCP migration of workloads",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"CI/CD setup for dockerized applications by provisioning Jenkins and efficient migration and cutover involving 17 servers and…",
		},
		{
			title: "Saving Costs & Scaling Better for Online Retail",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Cloud spend decreased by 15% overall Better manageability and lower operational overheads R,C, & E I Infra Mod",
		},
	],
	HLS: [
		{
			title: "Tendable: Infrastructure Modernization on Google Cloud",
			url: "https://www.searce.com/insights/case-studies",
			metrics: "Successfully reduced build time of new releases by almost 77%.",
		},
		{
			title: "Day 1 load conditions Total Processing: Setting up Scalable Infra Under Strict Timeline & COVID",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Successful Day 1 launch with site performing without any issues under Day 1 load conditions Total Processing is now setup with…",
		},
		{
			title: "Cloud Armor Customer: Improved Security & Latency for Healthcare",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Reduced cost upto 15% compared to previous cloud service Enhanced performance and latency with the help of cloud solutions…",
		},
	],
	MCM: [
		{
			title: "Connecting Wind Turbines to Increase Productivity",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Supports monitoring, reporting, and analytics for 2,000 wind turbines generating energy across several countries Gains ability…",
		},
		{
			title: "The Searce: AI enabled robot on GCP for Massage Robotics",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"This will be potentially disrupting a $12billion industry that has regularly received backlashes from users around economics,…",
		},
		{
			title: "It also: Conversational Chatbot",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"It also provides quick and automated answers to questions related to 15+ solar plans using Dialogflow.",
		},
	],
	TSS: [
		{
			title: "Manual process: Detection Modelling and Text Extraction",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Time to process one file manually is 5 to min min now it is done in less than a min This is a reusable solution that could be…",
		},
		{
			title: "They have workloads that: Scaling up on GCP effortlessly",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"10x increase in capacity while the right tradeoff between cost and performance.",
		},
		{
			title: "Improving Scalability & DR on GCP",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Platform Tech Stack Increased scalability with reduced operational overhead ~20% Cost Reduction Seamless Transition ISVs |…",
		},
	],
	PSE: [
		{
			title: "Difficulty with scaling: Complete Revamp on GCP with Searce",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Enabled 24% savings on infrastructure costs per month Helps increase throughput by 8% to provide almost immediate insights for…",
		},
		{
			title: "Migration of applications to GCP app engine & VM",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Post migration on GCP app engine it helps to Prof Jim save upto 95 % savings on cost.",
		},
		{
			title: "Technical: Improving Security Posture for Soccer Learning App",
			url: "https://www.searce.com/insights/case-studies",
			metrics:
				"Fully Secured Infrastructure avoiding any security breaches Automated infrastructure provisioning and hence increased…",
		},
	],
};
